version: "3"

services:
  vector:
    build: .
    network_mode: host
    hostname: "organization-project-instance"
    environment:
      EC_ORG: organization
      EC_PROJ: project
      EC_INST: instance

      APACHE_SCRAPE_INTERVAL: "10"
      APACHE_SCRAPE_ENDPOINT: "http://localhost:8008/server-status/?auto"
      APACHE_LOG_TYPE: "common"

      XP_SCRAPE_INTERVAL: "10"

      HOST_SCRAPE_INTERVAL: "10"
      HOST_SCRAPE_DISK_DEVICE: nvme0n1
      HOST_SCRAPE_NETWORK_DEVICE: wlp59s0

      BACKUP_SCRAPE_INTERVAL: "10"

    volumes:
      - ./config:/etc/vector:ro
      - vector:/var/lib/vector
      - /var/run/docker.sock:/var/run/docker.sock

  exp:
    image: enonic/xp:7.8.4-ubuntu
    container_name: exp
    labels:
      io.enonic.backup.prescripts: /usr/local/bin/backup.sh
    ports:
      - 2609:2609
      - 8080:8080
    volumes:
      - blobstore:/enonic-xp/home/repo/blob
      - snapshots:/enonic-xp/home/snapshots

  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - 8008:80
    volumes:
      - ./tests/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro

  backup:
    image: ghcr.io/enonic-cloud/ec-backup-agent:0.6.0
    container_name: backup
    hostname: "organization-project-instance"
    environment:
      RESTIC_REPOSITORY: /backups
      RESTIC_PASSWORD: secretpass
      AGENT_BACKUP_SCHEDULE: "* * * * *"
      AGENT_CLEANUP_RETENTION: 1h
      AGENT_CLEANUP_DAYS: "0 1 2 3 4 5 6"
    ports:
      - 8000:8000
    volumes:
      - backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro

volumes:
  backups:
  vector:
  blobstore:
    labels:
      io.enonic.backup.data: true
  snapshots:
    labels:
      io.enonic.backup.data: true