# EXPECTS:  <NONE>
# PROVIDES: metrics_exp_jvm_gc

sources:
  private_metrics_exp_jvm_gc_raw:
    type: exec
    mode: scheduled
    scheduled:
      exec_interval_secs: ${XP_SCRAPE_INTERVAL:-30}
    command: ["xp_metrics", "jvm.gc"]
    decoding:
      codec: json

transforms:
  metrics_exp_jvm_gc:
    type: log_to_metric
    inputs:
      - private_metrics_exp_jvm_gc_raw
    metrics:
      - type: counter
        field: collectionCount
        name: jvm_gc_count
        namespace: xp
        increment_by_value: true
        tags:
          collector: jvm.gc
          host: ${HOSTNAME}
      - type: counter
        field: collectionTime
        name: jvm_gc_time
        namespace: xp
        increment_by_value: true
        tags:
          collector: jvm.gc
          host: ${HOSTNAME}