# EXPECTS:  <NONE>
# PROVIDES: logs_unprocessed_exp

sources:
  private_logs_exp_orginal:
    type: docker_logs
    include_containers:
      - ${XP_CONTAINER_NAME:-exp}
    multiline:
      start_pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
      mode: halt_before
      condition_pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
      timeout_ms: 2000

transforms:
  private_logs_exp_basic:
    type: remap
    inputs:
      - private_logs_exp_orginal
    source: |-
      .namespace = "xp"

  logs_unprocessed_exp:
    type: remap
    inputs:
      - private_logs_exp_basic
    source: |-
      .message = strip_ansi_escape_codes!(.message)
      .parsed = parse_grok!(.message, "%{TIMESTAMP_ISO8601:timestamp}%{SPACE}%{LOGLEVEL:level}%{SPACE}%{NOTSPACE:class}%{SPACE}\\-%{SPACE}(?<message>(.|\r|\n)*)")
      .message = .parsed.message
      .class = .parsed.class
      .level = .parsed.level
      .timestamp = parse_timestamp!(.parsed.timestamp, "%F %T,%3f")

      del(.parsed)